[package]
name = "ashab_gps"
version = "0.1.0"
authors = ["David Pello <dpello@laboralcentrodearte.org>"]

[dependencies]
serial = "0.3.4"
spidev = "0.3.0"

[[bin]]
name = "test"
path = "src/test.rs"
